"""init

Revision ID: f4b3016b6ea8
Revises: 
Create Date: 2025-05-17 13:16:48.966056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b3016b6ea8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('ACCOUNTING', name='assistanttype'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attemps', sa.Integer(), nullable=True),
    sa.Column('settlement_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('settlement_transaction_count', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.String(length=255), nullable=True),
    sa.Column('attachment_id', sa.String(length=255), nullable=True),
    sa.Column('visa_net_report_file_name', sa.String(length=255), nullable=True),
    sa.Column('fac_report_file_name', sa.String(length=255), nullable=True),
    sa.Column('fac_start_date', sa.Date(), nullable=True),
    sa.Column('fac_start_time', sa.Time(), nullable=True),
    sa.Column('fac_end_date', sa.Date(), nullable=True),
    sa.Column('fac_end_time', sa.Time(), nullable=True),
    sa.Column('fac_report_transaction_count', sa.Integer(), nullable=True),
    sa.Column('fac_report_transaction_total', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('settlement_status', sa.Enum('New', 'Processing', 'Completed', name='settlementstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settlement_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement')
    op.drop_table('assistant')
    # ### end Alembic commands ###
